# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  deploy:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install git
          command: apt-get -qq update; apt-get -y install git

      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run:
          name: Clone then push to other repository if exists tag
          command: |
            ./mirror-push.sh "nendSDK-Document-Private" "nendSDK-Document-Private.wiki"

workflows:
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
